export const data: any = [
  {
    companyName: "ZENPHONE (ASUS)",
    merchantId: 1010005,
    name: "ZENPHONE (ASUS)",
  },
  {
    companyName: "ZENPHONE (ASUS)",
    merchantId: 1010005,
    name: "ZENPHONE (ASUS)",
  },
  {
    companyName: "SAMIK",
    merchantId: 1008701,
    name: "SAMIK",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "NAKYDACO",
    merchantId: 1007867,
    name: "NAKYDACO",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "HOÀNGPHÚCPHARMA",
    merchantId: 1006819,
    name: "HOÀNGPHÚCPHARMA",
  },
  {
    companyName: "COVER",
    merchantId: 1005847,
    name: "COVER",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "Thế giới di động 2",
    merchantId: 1010125,
    name: "Thế giới di động 1",
  },
  {
    companyName: "MQ",
    merchantId: 1007817,
    name: "MQ",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "SUNKIST",
    merchantId: 1009006,
    name: "SUNKIST",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "LU",
    merchantId: 1007502,
    name: "LU",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "Thế giới di động 2",
    merchantId: 1010126,
    name: "Thế giới di động 1",
  },
  {
    companyName: "CORSAIR",
    merchantId: 1005838,
    name: "CORSAIR",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "shopkinhdoanh@mwg.com",
    merchantId: 1010138,
    name: "shopkinhdoanh@mwg.com",
  },
  {
    companyName: "VANTELIN",
    merchantId: 1000560,
    name: "VANTELIN",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "Công ty VUIVUI",
    merchantId: 1009870,
    name: "Tên shop Test 29.04",
  },
  {
    companyName: "KIRKLAND",
    merchantId: 1007213,
    name: "KIRKLAND",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "THE COFFEE HOUSE",
    merchantId: 1009193,
    name: "THE COFFEE HOUSE",
  },
  {
    companyName: "homnaykhongcobug@mwg.com",
    merchantId: 1010140,
    name: "Hôm nay không bug",
  },
  {
    companyName: "Hôm nay có nhiều bug",
    merchantId: 1010141,
    name: "homnaycobug@tgdd.com",
  },
  {
    companyName: "DMX",
    merchantId: 1006026,
    name: "DMX",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "DANISCO",
    merchantId: 1001266,
    name: "DANISCO",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "DOVE",
    merchantId: 1006084,
    name: "DOVE",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "MEDIBIOS",
    merchantId: 1007634,
    name: "MEDIBIOS",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "ALCHAN JAERAE KIM",
    merchantId: 1005117,
    name: "ALCHAN JAERAE KIM",
  },
  {
    companyName: "LIÊN DOANH VIỆT ANH",
    merchantId: 1007421,
    name: "LIÊN DOANH VIỆT ANH",
  },
  {
    companyName: "ZUNE",
    merchantId: 1009821,
    name: "ZUNE",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "LUXTER",
    merchantId: 1007519,
    name: "LUXTER",
    representativeName: "Nguyễn Văn A",
  },
  { companyName: "Công ty ADEVA", merchantId: 1010027, name: "Adeva Noni" },
  {
    companyName: "Tân bực",
    merchantId: 1010076,
    name: "Tân bực",
    representativeName: "Tân Bực",
  },
  {
    companyName: "GSK",
    merchantId: 1006632,
    name: "GSK",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "ZYCOM",
    merchantId: 1009822,
    name: "ZYCOM",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "Shop 123",
    merchantId: 1010136,
    name: "Shop 123",
    representativeName: "Nguyễn B",
  },
  { companyName: "thu2dautuan@mwg.com", merchantId: 1010142, name: "Thứ 2" },
  {
    companyName: "NEPTUNE",
    merchantId: 1007935,
    name: "NEPTUNE",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "",
    merchantId: 1010143,
    name: "hnay vui quá",
    representativeName: "Vui",
  },
  {
    companyName: "",
    merchantId: 1010137,
    name: "ác đà à",
    representativeName: "asf asf a. đà",
  },
  {
    companyName: "ME-O",
    merchantId: 1007622,
    name: "ME-O",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "MUAYTHAI",
    merchantId: 1007832,
    name: "MUAYTHAI",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "SAITU",
    merchantId: 1008692,
    name: "SAITU",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "MOONY",
    merchantId: 1007796,
    name: "MOONY",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "AXON",
    merchantId: 1005314,
    name: "AXON",
    representativeName: "Nguyễn Văn A",
  },
  { companyName: "abc@tgdd.mwgcom", merchantId: 1010144, name: "ABCMWG" },
  {
    companyName: "Thế giới di động 2",
    merchantId: 1010111,
    name: "Thế giới di động 1",
  },
  {
    companyName: "CP",
    merchantId: 1005852,
    name: "CP",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "AGURI",
    merchantId: 1005087,
    name: "AGURI",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "CÔ THẮM",
    merchantId: 1005787,
    name: "CÔ THẮM",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "testshopstatus@mwg.com",
    merchantId: 1010145,
    name: "Shop Status",
  },
  {
    companyName: "CALSOME",
    merchantId: 1000988,
    name: "CALSOME",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "",
    merchantId: 1010146,
    name: "Anna House",
    representativeName: "An Hoang",
  },
  {
    companyName: "EVALU",
    merchantId: 1006305,
    name: "EVALU",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "FORME",
    merchantId: 1006416,
    name: "FORME",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "MWG company",
    merchantId: 12,
    name: "Merchant 12",
    representativeName: "Lee Faker hear",
  },
  {
    companyName: "MWG test IT Nhun",
    merchantId: 240,
    name: "VuiGhe",
    representativeName: "",
  },
  {
    companyName: "yyyyyy",
    merchantId: 1010147,
    name: "yyyyyy",
    representativeName: "yyyy",
  },
  { companyName: "NANANA BOAT", merchantId: 1000816, name: "NANANA BOAT" },
  { companyName: "MILKY DRESS", merchantId: 1007726, name: "MILKY DRESS" },
  {
    companyName: "SPERLARI",
    merchantId: 1008933,
    name: "SPERLARI",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "BORDEN",
    merchantId: 1000933,
    name: "BORDEN",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "",
    merchantId: 1010064,
    name: "suka shop",
    representativeName: "sizuka",
  },
  {
    companyName: "KOPIKO",
    merchantId: 1007256,
    name: "KOPIKO",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "SPM",
    merchantId: 1008938,
    name: "SPM",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "BEEVIN",
    merchantId: 1005412,
    name: "BEEVIN",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "ABTEI OP PHARMA",
    merchantId: 1005048,
    name: "ABTEI OP PHARMA",
  },
  {
    companyName: "VASELINE",
    merchantId: 1000607,
    name: "VASELINE",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "OKF",
    merchantId: 1008130,
    name: "OKF",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "HATARI",
    merchantId: 1006732,
    name: "HATARI",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "COLGATE",
    merchantId: 1000649,
    name: "COLGATE",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "BAGO",
    merchantId: 1005346,
    name: "BAGO",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "GREEN'S A",
    merchantId: 1006619,
    name: "GREEN'S A",
    representativeName: "Nguyễn Văn A",
  },
  { companyName: "CATHY DOLL", merchantId: 1000769, name: "CATHY DOLL" },
  {
    companyName: "SEN VIỆT",
    merchantId: 1008789,
    name: "SEN VIỆT",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "ROPPY",
    merchantId: 1008622,
    name: "ROPPY",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "PROTEX",
    merchantId: 1000774,
    name: "PROTEX",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "KATZ",
    merchantId: 1007133,
    name: "KATZ",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "MIHOO",
    merchantId: 1007716,
    name: "MIHOO",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "BOXI",
    merchantId: 1000951,
    name: "BOXI",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "Á ÂU",
    merchantId: 1005024,
    name: "Á ÂU",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "LIÊN KẾT",
    merchantId: 1000552,
    name: "LIÊN KẾT",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "LAGO",
    merchantId: 1007337,
    name: "LAGO",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "REBIRTH",
    merchantId: 1000829,
    name: "REBIRTH",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "CILAG",
    merchantId: 1005754,
    name: "CILAG",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "BEI YU",
    merchantId: 1005414,
    name: "BEI YU",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "COOL AIR",
    merchantId: 1001172,
    name: "COOL AIR",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "LACTACYCL",
    merchantId: 1000882,
    name: "LACTACYCL",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "NAM HÙNG PHƯƠNG",
    merchantId: 1007876,
    name: "NAM HÙNG PHƯƠNG",
  },
  {
    companyName: "PEGA",
    merchantId: 1008283,
    name: "PEGA",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "BONCHEF",
    merchantId: 1000926,
    name: "BONCHEF",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "HELLEMA",
    merchantId: 1006757,
    name: "HELLEMA",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "MISSHA",
    merchantId: 1007750,
    name: "MISSHA",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "",
    merchantId: 1010067,
    name: "VuiVui Test",
    representativeName: "VuiVui Test",
  },
  {
    companyName: "BESINS",
    merchantId: 1005447,
    name: "BESINS",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "KIN",
    merchantId: 1007194,
    name: "KIN",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "CAMEL",
    merchantId: 1005627,
    name: "CAMEL",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "GROTEX",
    merchantId: 1006629,
    name: "GROTEX",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "KHÔNG ĐỘ",
    merchantId: 1007171,
    name: "KHÔNG ĐỘ",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "CANDIPHA",
    merchantId: 1000997,
    name: "CANDIPHA",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "TAVI",
    merchantId: 1009115,
    name: "TAVI",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "TP-LINK",
    merchantId: 1009302,
    name: "TP-LINK",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "DARLING",
    merchantId: 1001270,
    name: "DARLING",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "DONALD",
    merchantId: 1006043,
    name: "DONALD",
    representativeName: "Nguyễn Văn A",
  },
  {
    companyName: "Thế giới di động 2",
    merchantId: 1010123,
    name: "Thế giới di động 1",
  },
];
